
janela: janela.cpp
	g++ -I .. -o janela \
		`pkg-config --cflags gtk4` \
		../uigtk.cpp janela.cpp \
		`pkg-config --libs gtk4`

label: label.cpp
	g++ -I .. -o label \
		`pkg-config --cflags gtk4` \
		../uigtk.cpp label.cpp \
		`pkg-config --libs gtk4`

vbox: vbox.cpp
	g++ -I .. -o vbox \
		`pkg-config --cflags gtk4` \
		../uigtk.cpp vbox.cpp \
		`pkg-config --libs gtk4`